# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, ... }:

{

  systemd.services.nvidia-control-devices = {
    wantedBy = [ "multi-user.target" ];
    serviceConfig.ExecStart = "${pkgs.linuxPackages.nvidia_x11.bin}/bin/nvidia-smi";
  };

  hardware = {
    graphics.enable = true;
    bluetooth = {
      enable = true;
      package = pkgs.bluez;
      powerOnBoot = true;
      settings = {
        General = {
          Experimental = true;
          KernelExperimental = true;
          FastConnectable = true;
          Class = "0x000100";
        };
      };
    };


    pulseaudio.configFile = pkgs.writeText "default.pa" ''
      load-module module-bluetooth-policy
      load-module module-bluetooth-discover a2dp_config="ldac_eqmid=sq"
      load-module module-bluez5-device
      load-module module-bluez5-discover
      load-module module-switch-on-connect
    '';

    nvidia = {
      open = false;
      package = config.boot.kernelPackages.nvidiaPackages.stable;

      powerManagement.enable = true;
      nvidiaSettings = true;

      modesetting.enable = true;
      prime = {
        sync.enable = true;
        nvidiaBusId = "PCI:01:0:0";
        amdgpuBusId = "PCI:65:0:0"; 
      };
    };
  };
}
