# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  pkgs,
  ...
}: {
  boot.extraModprobeConfig = ''
    options nvidia NVreg_EnablePCIeGen3=1
    options nvidia NVreg_UsePageAttributeTable=1
    options nvidia NVreg_EnableGpuFirmware=0
    options nvidia-drm modeset=1
  '';
  systemd.services.nvidia-control-devices = {
    wantedBy = ["multi-user.target"];
    serviceConfig.ExecStart = "${pkgs.linuxPackages.nvidia_x11.bin}/bin/nvidia-smi";
  };

  hardware = {
    graphics.enable = true;
    bluetooth = {
      enable = true;
      package = pkgs.bluez-experimental;
      powerOnBoot = true;
      settings = {
        General = {
          Experimental = true;
          KernelExperimental = true;
          FastConnectable = false;
          MultiProfile = "multiple";
        };

        Plugins = {
          a2dp = true;
          policy = true;
          media = true;
          hostname = true;
          avrcp = true;
        };
      };
    };
    nvidia = {
      open = false;
      package = config.boot.kernelPackages.nvidiaPackages.stable;

      powerManagement = {
        enable = true;
        finegrained = false; # Changed from true - prevents D3cold sleep state causing HDMI issues
      };

      nvidiaSettings = true;

      modesetting.enable = true;
      prime = {
        sync.enable = false;
        nvidiaBusId = "PCI:01:0:0";
        amdgpuBusId = "PCI:65:0:0";
        offload = {
          enable = true;
          enableOffloadCmd = true; # Enable nvidia-offload command
        };
      };
    };
  };
}
