# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{pkgs, ...}: {
  boot.extraModprobeConfig = ''
    options nvidia NVreg_UsePageAttributeTable=1
    options nvidia-drm modeset=1
  '';
  systemd.services.nvidia-control-devices = {
    wantedBy = ["multi-user.target"];
    serviceConfig.ExecStart = "${pkgs.linuxPackages.nvidia_x11.bin}/bin/nvidia-smi";
  };

  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true; # Required for Steam and 32-bit applications
    };
    bluetooth = {
      enable = true;
      package = pkgs.bluez-experimental;
      powerOnBoot = true;
      settings = {
        General = {
          Experimental = true;
          KernelExperimental = true;
          FastConnectable = false;
          MultiProfile = "multiple";
        };

        Plugins = {
          a2dp = true;
          policy = true;
          media = true;
          hostname = true;
          avrcp = true;
        };
      };
    };
    nvidia = {
      open = false;

      powerManagement = {
        enable = true;
        finegrained = false; # Changed from true - prevents D3cold sleep state causing HDMI issues
      };

      nvidiaSettings = true;

      prime = {
        sync.enable = false;
        nvidiaBusId = "PCI:01:0:0";
        amdgpuBusId = "PCI:65:0:0";
        offload = {
          enable = true;
          enableOffloadCmd = true; # Enable nvidia-offload command
        };
      };
    };
  };
}
